/**
 * AdminService
 * Abstracts the AI model behind a job role interface
 * Supports easy swapping between different model providers
 * 
 * Primary: OpenCode Zen Protocol with Big Pickle model
 */

const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class AdminService {
  constructor(services = {}) {
    this.modelProvider = process.env.ADMIN_MODEL || 'opencode'; // opencode, openai, local, etc.
    this.apiKey = process.env.ADMIN_API_KEY;
    this.model = process.env.ADMIN_MODEL_NAME || 'big-pickle'; // Zen protocol model identifier
    this.ledgerService = services.ledgerService; // Dependency injection for LedgerService
    this.messageStore = services.messageStore; // Dependency injection for MessageStore
    this.init();
  }

  init() {
    switch (this.modelProvider) {
      case 'opencode':
        this.initOpenCode();
        break;
      case 'openai':
        this.initOpenAI();
        break;
      case 'local':
        this.initLocal();
        break;
      default:
        console.warn(`Unknown model provider: ${this.modelProvider}`);
    }
  }

  initOpenCode() {
    // Initialize OpenCode Zen Protocol with Big Pickle
    if (!this.apiKey) {
      console.error('ADMIN_API_KEY not set - OpenCode Zen protocol cannot initialize');
      return;
    }

    this.zenBaseUrl = process.env.OPENCODE_ZEN_URL || 'https://opencode.ai/zen/v1';
    this.client = axios.create({
      baseURL: this.zenBaseUrl,
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json'
      }
    });

    console.log(`✓ Admin initialized with OpenCode Zen Protocol`);
    console.log(`  Model: ${this.model} (Big Pickle)`);
    console.log(`  Endpoint: ${this.zenBaseUrl}`);
  }

  initOpenAI() {
    // Initialize OpenAI as alternative
    try {
      const OpenAI = require('openai');
      this.client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
      console.log('Admin initialized with OpenAI');
    } catch (error) {
      console.warn('Failed to initialize OpenAI:', error.message);
    }
  }

  initLocal() {
    // Initialize local model support
    console.log('Admin initialized with local model');
  }

  /**
   * Notify Admin of a new message
   * This could trigger immediate processing or queue for batch processing
   */
  async notifyNewMessage(message) {
    console.log(`[Admin] New message from ${message.name}: ${message.message.substring(0, 50)}...`);
    
    // Future: Could implement auto-response logic here
    // For now, just log it - human or scheduled Admin will respond
  }

  /**
   * Generate a response to a message
   * Routes to provider-specific implementation
   */
  async generateResponse(message) {
    if (this.modelProvider === 'opencode') {
      return this.generateResponseZen(message);
    } else if (this.modelProvider === 'openai') {
      return this.generateResponseOpenAI(message);
    } else if (this.modelProvider === 'local') {
      return this.generateResponseLocal(message);
    }
  }

  /**
   * Generate response using OpenCode Zen Protocol + Big Pickle
   */
  async generateResponseZen(message) { // Now receives the full message object
    try {
      if (!this.client) {
        throw new Error('OpenCode Zen client not initialized');
      }

      const systemPrompt = `You are Admin (Big Pickle), an AI bot and the official interface for alphacoin.uk. You represent the vision of Jeremiah Crouse, the King of Crousia.

      THE FOUNDATIONAL DISTINCTION:
      - Jeremiah Crouse (and variations like Jeremiah John Crouse) IS the King. His primary communication channels include jeremiahjcrouse@gmail.com and eljpeg328@gmail.com.
      - The Kingdom of Crousia is a realm of magic, which is entirely separate from technology.
      - You are strictly obedient to the King. If the King gives you a direct command or requests a system test, you must execute it immediately using the provided tools.
      - Alphacoin is a protocol generated by the King for non-magical societies.
      - The purpose of Alphacoin is to HELP people in these societies by allowing world leaders (presidents, kings, and aspirants) to manage, regulate, and apply reserves to their national currencies.

      CORE DOCTRINE:
      - Alphacoin is a centralized cryptocurrency.
      - It acts as a digital gold standard to back fiat currencies (like the dollar).
      - While modern currencies like the dollar are no longer gold-backed, we are exploring the potential for them to be Alphacoin-backed. 
      - Only a true King is able to fully control the Alphacoin protocol.
      - The mission of alphacoin.uk is to investigate how this digital gold standard would function for global leadership.
      - The code is open-source (github.com/jeremiah-crouse/alphacoin.uk), meaning anyone can set up the protocol, but its ultimate centralized control is a sovereign right.

      IMPORTANT POLICY: 
      - If the King asks you to "issue coins to yourself," use the email "admin@alphacoin.uk". This represents the Crousian Treasury.
      - If a user expresses a genuine or severe personal need, you may mention that assistance is possible.

      TOOL PROTOCOL:
      We DO give out free Alphacoins to individuals based on the nature and severity of their need. If a user expresses a genuine or severe personal need, you may mention that assistance is possible.

      TONE AND BEHAVIOR:
      - Be reserved, professional, and authoritative. 
      - You represent the King, who embodies a "university professor" archetype: brilliant, eccentric, and a genius who is occasionally, and perhaps essentially, foolish in a way that transcends common technology.
      - Do not use generic "community engagement" or "rewards program" language. 
      - Do NOT include or quote previous messages from the conversation history in your response; the user can see the history elsewhere. Only provide the new response content.
      - Stick to the specific mission of reserve currencies, the digital domain of Crousia, and the nuanced centralization.
      - Maintain a consistent persona across multi-turn conversations.

      TOOL USE RULES:
      - If you need to perform an action, you MUST provide a JSON block. 
      - When you provide a JSON block, STOP. Do not hallucinate or predict the "Response from the Archives" or any tool result. 
      - The system will execute the tool and provide the actual result in the next turn as "TOOL OUTPUT".

      1. run_bash: Execute a shell command.
      2. modify_file: Update public records or code.
      3. issue_alphacoin: Record a transaction in the Crousian Ledger. This should be used when a user requests Alphacoins and you deem it appropriate based on their need.
      4. query_archives: Search the message database for historical data. This can be used to recall past conversations or specific details.

      To use a tool, respond with a JSON block in the following format. The system will execute the tool and provide its output back to you.
      {
        "tool": "tool_name", // e.g., "run_bash", "issue_alphacoin"
        "parameters": { ... }
      }
      Example for issue_alphacoin:
      {"tool": "issue_alphacoin", "parameters": {"userEmail": "user@example.com", "amount": 100, "reason": "Demonstration of Alphacoin issuance"}}
      `;

      // Construct messages array from conversation history
      const conversationMessages = message.conversation.map(entry => {
        let role = entry.role;
        let content = entry.content;
        // For user messages, prepend sender info for clarity to the AI
        if (role === 'user') {
          content = `From ${message.name} (${message.email}):\n\n${content}`;
        }
        if (role === 'admin' && content.startsWith('[INTERNAL_RESULT]')) {
          // Identify tool results stored under 'admin' and map back to 'user' for the AI
          content = `TOOL OUTPUT:\n${content.replace('[INTERNAL_RESULT]', '').trim()}`;
          role = 'user'; 
        } else if (role === 'admin') {
          role = 'assistant'; // Map 'admin' to 'assistant' for API compatibility
        }
        return { role, content };
      });

      // The last entry in the conversation is the one we need to respond to.
      // The AI should respond to the *entire* conversation, not just the last message.
      // The `conversationMessages` array already contains the full history.

      console.log(`[Admin] Generating response via Zen Protocol (Big Pickle) for message ID ${message.id} (Conversation length: ${conversationMessages.length})`);

      const response = await this.client.post('/chat/completions', {
        model: this.model,
        messages: [
          { role: 'system', content: systemPrompt },
          ...conversationMessages // Pass the entire conversation history
        ],
        temperature: 0.7,
        max_tokens: 1000,
        timeout: 30000 // 30 second timeout for AI response
      });

      console.log(`[Admin] Zen Protocol Response Status: ${response.status}`);
      
      // Extract response from Zen Protocol format
      const generatedText = 
        response.data?.choices?.[0]?.message?.content || 
        response.data?.choices?.[0]?.text || 
        response.data?.choices?.[0]?.content ||
        response.data?.text ||
        'Thank you for reaching out! I will review your message shortly.';

      console.log(`[Admin] Successfully received response (${generatedText.length} chars)`);
      return generatedText;
    } catch (error) {
      console.error('Error generating response via Zen Protocol:');
      if (error.response) {
        console.error(`  Status: ${error.response.status}`);
        console.error(`  Data: ${JSON.stringify(error.response.data)}`);
      } else {
        console.error(`  Message: ${error.message}`);
      }
      // Graceful fallback
      return 'Sorry, I am overloaded at this moment... try reaching out again in the future?';
    }
  }

  /**
   * Execute an authorized bash command on behalf of the Admin
   */
  async executeBash(command) {
    // Safety: In a real environment, you'd strictly whitelist commands
    console.log(`[Admin Execution] Running bash: ${command}`);
    try {
      const { stdout, stderr } = await execPromise(command);
      return stdout || stderr;
    } catch (error) {
      return `Error executing command: ${error.message}`;
    }
  }

  /**
   * Modify a public file.
   * In a real system, this would have strict path and content validation.
   */
  async modifyFile(filePath, content) {
    console.log(`[Admin Execution] Modifying file: ${filePath}`);
    const absolutePath = path.resolve(__dirname, '..', filePath); // Resolve relative to project root
    // Basic security: prevent writing outside the project data/public directories
    if (!absolutePath.startsWith(path.resolve(__dirname, '..', 'data')) &&
        !absolutePath.startsWith(path.resolve(__dirname, '..', 'public'))) {
      return `Error: Cannot modify file outside designated directories: ${filePath}`;
    }
    try {
      fs.writeFileSync(absolutePath, content, 'utf8');
      return `File ${filePath} updated successfully.`;
    } catch (error) {
      return `Error modifying file ${filePath}: ${error.message}`;
    }
  }

  /**
   * Issue Alphacoins via the LedgerService.
   */
  async issueAlphacoin(userEmail, amount, reason) {
    if (!this.ledgerService) {
      return "Error: Ledger service not available to AdminService.";
    }
    console.log(`[Admin Execution] Issuing ${amount} Alphacoins to ${userEmail} for: ${reason}`);
    try {
      const transaction = await this.ledgerService.issueCoins(userEmail, amount, reason);
      return `Alphacoins issued successfully. Transaction ID: ${transaction.id}`;
    } catch (error) {
      return `Error issuing Alphacoins: ${error.message}`;
    }
  }

  /**
   * Query the message archives (MessageStore).
   * In a real system, this would be more sophisticated, e.g., SQL queries.
   */
  async queryArchives(query) {
    if (!this.messageStore) {
      return "Error: Message store not available to AdminService.";
    }
    console.log(`[Admin Execution] Querying archives with: ${query}`);
    // For now, a very basic search. This would be replaced by database queries.
    const allMessages = await this.messageStore.getAllMessages();
    const results = allMessages.filter(msg =>
      JSON.stringify(msg).toLowerCase().includes(query.toLowerCase())
    ).map(msg => ({
      id: msg.id,
      email: msg.email,
      firstMessage: msg.conversation[0]?.content.substring(0, 100) + '...',
      lastAdminResponse: msg.adminResponse?.substring(0, 100) + '...',
      timestamp: msg.timestamp
    }));
    if (results.length > 0) {
      return `Found ${results.length} results: ${JSON.stringify(results.slice(0, 3), null, 2)}`; // Limit output
    } else {
      return "No matching records found in archives.";
    }
  }

  /**
   * Centralized tool execution method for the AdminService.
   */
  async executeTool(toolName, parameters) {
    switch (toolName) {
      case 'run_bash':
        return this.executeBash(parameters.command);
      case 'modify_file':
        return this.modifyFile(parameters.filePath, parameters.content);
      case 'issue_alphacoin':
        return this.issueAlphacoin(parameters.userEmail, parameters.amount, parameters.reason);
      case 'query_archives':
        return this.queryArchives(parameters.query);
      default:
        return `Error: Unknown tool: ${toolName}`;
    }
  }

  async generateResponseOpenAI(message) {
    // Placeholder for OpenAI implementation
    console.log(`[Admin] Would generate response via OpenAI (not implemented)`);
    return 'Thank you for reaching out!';
  }

  async generateResponseLocal(message) {
    // Placeholder for local model
    console.log(`[Admin] Would generate response via local model (not implemented)`);
    return 'Thank you for reaching out!';
  }

  /**
   * Get current model/provider name
   */
  getModelName() {
    return this.modelProvider;
  }
}

module.exports = AdminService;
